# Generated by Django 6.0.5 on 2026-06-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('expense_type', models.CharField(choices=[('処理場', '処理場'), ('その他', 'その他')], default='処理場', max_length=10, verbose_name='種別')),
                ('site_name', models.CharField(max_length=100, verbose_name='処理場名・内容')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='金額')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '経費',
                'verbose_name_plural': '経費',
                'ordering': ['-date', 'expense_type'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='処理場名')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': '処理場',
                'verbose_name_plural': '処理場',
                'ordering': ['name'],
            },
        ),
    ]
