# Generated by Django 6.0.5 on 2026-06-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('driver_name', models.CharField(max_length=50, verbose_name='ドライバー名')),
                ('job_type', models.CharField(choices=[('処分', '処分'), ('買取', '買取'), ('見積', '見積'), ('その他', 'その他')], max_length=10, verbose_name='仕事種類')),
                ('customer_name', models.CharField(max_length=100, verbose_name='お客様名')),
                ('place', models.CharField(blank=True, max_length=100, verbose_name='地名')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='金額')),
                ('time', models.CharField(blank=True, max_length=20, verbose_name='時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '作業記録',
                'verbose_name_plural': '作業記録',
                'ordering': ['-date', 'driver_name'],
            },
        ),
    ]
