# Generated by Django 6.0.5 on 2026-07-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_workrecord_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='削除済み'),
        ),
    ]
